### ISSUE TITLE
sftp copy enters exeption Timeout if catched signal (SIGHUP, SIGTERM) received (blocking mode)

### ISSUE THREAD

**Issue by LinLo** [ParallelSSH/ssh2-python#67]
### Bug reports

I'm writing a service (daemon) that do some tasks in background.
With signal module the service catches SIGHUP to do a reload of the configuration file.

If SIGHUP (or other signal like SIGINT, SIGTERM, SIGUSR1...), the sftp copy (and maybe every task currently in process over a ssh2 session) stops and terminate on exception Timeout.

__Steps to reproduce:__
1. Example code that produces error.
```
import os
import socket
import signal
from ssh2.session import Session
from ssh2.sftp import LIBSSH2_FXF_CREAT, LIBSSH2_FXF_WRITE, \
    LIBSSH2_SFTP_S_IRUSR, LIBSSH2_SFTP_S_IRGRP, LIBSSH2_SFTP_S_IWUSR, \
    LIBSSH2_SFTP_S_IROTH

def connect():
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(('10.0.0.1', 22))
    session = Session()
    session.handshake(sock)
    session.userauth_password('user', 'password')
    return (sock, session)

def copy_sftp(session, source, dest):
    sftp = session.sftp_init()
    mode = LIBSSH2_SFTP_S_IRUSR | \
           LIBSSH2_SFTP_S_IWUSR | \
           LIBSSH2_SFTP_S_IRGRP | \
           LIBSSH2_SFTP_S_IROTH
    f_flags = LIBSSH2_FXF_CREAT | LIBSSH2_FXF_WRITE
    with open(source, 'rb') as local_fh, \
            sftp.open(dest, f_flags, mode) as remote_fh:
        for data in local_fh:
            remote_fh.write(data)

def handler(signum, frame):
    print('Signal handler called with signal', signum)

if __name__ == '__main__':
    signal.signal(signal.SIGHUP, handler)
    sock, session = connect()
    copy_sftp(session, 'my_big_file', 'my_big_file')
```

2. Stack trace or error messages.
```
$ ./ssh_test.py 
Signal handler called with signal 1
Signal handler called with signal 1
Traceback (most recent call last):
  File "./ssh_test.py", line 44, in <module>
    copy_sftp(session, 'my_big_file', 'my_big_file')
  File "./ssh_test.py", line 34, in copy_sftp
    remote_fh.write(data)
  File "ssh2/sftp_handle.pyx", line 291, in ssh2.sftp_handle.SFTPHandle.write
  File "ssh2/utils.pyx", line 113, in ssh2.utils.handle_error_codes
ssh2.exceptions.Timeout
```
__Expected behaviour:__
I don't know what is the expected behaviour but how could I use signals with ssh2-python ?
When a SIG is catched by python signal, ssh2 should not stop his work with timeout exception.
Is this related to GIL ? May I have work with a non-blocking session ?

__Actual behaviour:__
sftp transfer failed and terminate with a timeout exception when a signal is received.

__Additional info:__ [Include version of ``libssh2`` and any other relevant information.]
libssh2 1.8.0
ssh2-python installed with pip

**Comment by LinLo** [comment]
Can't reproduce with SCP instead of SFTP:
```
def copy_scp(session, source, dest):
    fileinfo = os.stat(source)
    chan = session.scp_send64(dest, fileinfo.st_mode & 0o777, fileinfo.st_size,
                              fileinfo.st_mtime, fileinfo.st_atime)
    with open(source, 'rb') as local_fh:
        for data in local_fh:
            chan.write(data)
```
I will test with a channel.execute command that takes a while to see if this is related only to SFTP.

**Comment by LinLo** [comment]
Reproduced with an execute command (sleep 600), so not related only to sftp:
```
$ ./ssh_test.py 
Signal handler called with signal 1
Traceback (most recent call last):
  File "./ssh_test.py", line 69, in <module>
    execute_cmd(session)
  File "./ssh_test.py", line 50, in execute_cmd
    channel.wait_eof()
  File "ssh2/channel.pyx", line 197, in ssh2.channel.Channel.wait_eof
  File "ssh2/utils.pyx", line 113, in ssh2.utils.handle_error_codes
ssh2.exceptions.Timeout
```

```
def execute_cmd(session):
    channel = session.open_session()
    channel.execute('sleep 600')
    channel.wait_eof()
    channel.close()
    channel.wait_closed()
    print("Exit status: %s" % channel.get_exit_status())
    size, data = channel.read()
    while size > 0:
        print(data)
    size, data = channel.read()
```

**Comment by LinLo** [comment]
Can't reproduce with execute on a non-blocking session with wait_socket:
```
def execute_cmd_non_blocking(sock, session):
    session.set_blocking(False)
    chan = session.open_session()
    while chan == LIBSSH2_ERROR_EAGAIN:
        print("Would block on session open, waiting for socket to be ready")
        wait_socket(sock, session)
        chan = session.open_session()
    while chan.execute('sleep 600') == LIBSSH2_ERROR_EAGAIN:
        print("Would block on channel execute, waiting for socket to be ready")
        wait_socket(sock, session)
    while chan.wait_eof() == LIBSSH2_ERROR_EAGAIN:
        print("Waiting for command to finish")
        wait_socket(sock, session)
    size, data = chan.read()
    while size == LIBSSH2_ERROR_EAGAIN:
        print("Waiting to read data from channel")
        wait_socket(sock, session)
        size, data = chan.read()
    while size > 0:
        print(data)
        size, data = chan.read()
```

**Comment by LinLo** [comment]
Can't reproduce with sftp non blocking. Is there a better way to work in production with non blocking sftp ?

```
def copy_sftp_nb(sock, session, source, dest):
    sftp = session.sftp_init()
    mode = LIBSSH2_SFTP_S_IRUSR | \
           LIBSSH2_SFTP_S_IWUSR | \
           LIBSSH2_SFTP_S_IRGRP | \
           LIBSSH2_SFTP_S_IROTH
    f_flags = LIBSSH2_FXF_CREAT | LIBSSH2_FXF_WRITE | LIBSSH2_FXF_TRUNC
    remote_fh = sftp.open(dest, f_flags, mode)
    with sftp.open(dest, f_flags, mode) as remote_fh:
        session.set_blocking(False)
        with open(source, 'rb') as local_fh:
            data = local_fh.read(32728)
            while True:
                if not data:
                    break
                rc, bytes_written = remote_fh.write(data)
                while rc == LIBSSH2_ERROR_EAGAIN and bytes_written != len(data):
                    rc, next_written = remote_fh.write(data[bytes_written:])
                    bytes_written += next_written
                data = local_fh.read(32728)
        wait_socket(sock, session)
```

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest.

This seems like expected behaviour. The session is being run in the same thread as signal handler. When the signal triggers, the thread gets interrupted to run signal handling code. This causes the socket operation that was being executed to stop which causes a timeout in blocking mode. Same will happen with anything else doing blocking calls, socket operations, file I/O etc.

This does not happen in non-blocking mode, again as expected.

Would suggest either running the ssh2-python code in a separate thread - and to be clear, all ssh2-python code, sessions cannot be shared across threads - or run in non-blocking mode as above. Do not see an issue with ssh2-python.
