### ISSUE TITLE
Unable to connect to agent

### ISSUE THREAD

**Issue by github-of-dl** [ParallelSSH/ssh2-python#72]
### Bug reports

__Steps to reproduce:__

1. Example code that produces error.
```
from ssh2.session import Session

import socket

sock=socket.socket(socket.AF_INET, socket.SOCK_STREAM);
sock.connect( ('localhost', 22) );

session=Session();
session.agent_init();
session.handshake(sock);

session.agent_auth('z');
```
2. Stack trace or error messages.
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    session.agent_auth('z');
  File "ssh2/session.pyx", line 309, in ssh2.session.Session.agent_auth
  File "ssh2/agent.pyx", line 84, in ssh2.agent.init_connect_agent
ssh2.exceptions.AgentConnectionError: Unable to connect to agent
```

__Expected behaviour:__
pass the authentication

__Actual behaviour:__ 

__Additional info:__ 
ssh2-python: 0.17.0
libssh2-1.4.3-10.el7.x86_64

**Comment by pkittenis** [comment]
Hi there,

Thanks for the interest. Is agent running? Unable to connect means what it says.

**Comment by sadamasin** [comment]
I'm facing same issue, Windows 10, Python 3.6.5.
I've tried running agent from Git Bash and Powershell but nothing changed.

`>>> session.agent_init()
<ssh2.agent.Agent object at 0x0000020B2F5BF0B8>
>>> session.agent_auth(user)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ssh2\session.pyx", line 306, in ssh2.session.Session.agent_auth
  File "ssh2\agent.pyx", line 84, in ssh2.agent.init_connect_agent
ssh2.exceptions.AgentConnectionError: Unable to connect to agent`

**Additional info:**
ssh2-python==0.18.0.post1

**Comment by SouravKB** [comment]
I'm facing the same issue, Ubuntu16.04, Python3.5, ssh2-python1.0.0
```
>>> session.agent_auth(user)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ssh2/session.pyx", line 375, in ssh2.session.Session.agent_auth
  File "ssh2/agent.pyx", line 84, in ssh2.agent.init_connect_agent
ssh2.exceptions.AgentConnectionError: Unable to connect to agent
```
