### ISSUE TITLE
ssh2.channel.Channel.close

### ISSUE THREAD

**Issue by ankitjain87** [ParallelSSH/ssh2-python#82]
This is an intermittent issue, there is no actual reason why this is happening. The code is executed every 2 mins, and this error occurred once or twice every hour.

__Steps to reproduce:__

1. Example code that produces an error.
```
def execute_command(hostname, command):
    channel = None
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.connect((hostname, 22))
        ses = Session()
        ses.set_timeout(SSH_COMMAND_TIMEOUT)
        ses.handshake(sock)
        ses.userauth_password(USER, PASSWORD)
        channel = ses.open_session()
        channel.execute(command)
        size, output = channel.read()
        return size, output
    except ssh2.exceptions.ChannelError:
        LOGGER.error('%s | ChannelError' % hostname)
    except ssh2.exceptions.AgentConnectionError:
        LOGGER.error('%s | Error connecting to host' % hostname)
    except ssh2.exceptions.AgentListIdentitiesError:
        LOGGER.error('%s | Agent List identities error' % hostname)
    except ssh2.exceptions.AgentAuthenticationError:
        LOGGER.error('%s | Authentication Error' % hostname)
    except ssh2.exceptions.Timeout as ex:
        LOGGER.error("SSH Timeout for {}: {}".format(hostname, str(ex)))
    except Exception as ex:
        LOGGER.error("Some exception; {}".format(str(ex)))
    finally:
        if channel:
            channel.close()
```

2. Stack trace or error messages.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/utils/cors.py", line 35, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/project/api.py", line 71, in get
    info = future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/project/api.py", line 191, in get_info
    size, output = execute_command(hostname, command)
  File "/project/api.py", line 185, in execute_command
    channel.close()
  File "ssh2/channel.pyx", line 204, in ssh2.channel.Channel.close
  File "ssh2/utils.pyx", line 113, in ssh2.utils.handle_error_codes
ssh2.exceptions.Timeout```

__Additional info:__ [Include version of ``libssh2`` and any other relevant information.]
Python-3.6.0
ssh2-python==0.17.0

This is running inside a docker.

Thanks!

**Comment by pkittenis** [comment]
Thanks for the interest. Not sure what is being reported here. The example code seems to be handling a timeout and printing stack trace of when it occurred.
