### ISSUE TITLE
SocketRecvError

### ISSUE THREAD

**Issue by brunotissi** [ParallelSSH/ssh2-python#83]
### Sometimes I get a SocketRcvError after the script execution

Traceback (most recent call last):
  File "C:/Users/btissi/PycharmProjects/Test/script_4_test.py", line 41, in <module>
    for line in host_output.stdout:
  File "C:\Users\btissi\PycharmProjects\Test\venv\lib\site-packages\pssh\clients\native\single.py", line 401, in read_output_buffer
    for line in output_buffer:
  File "pssh/native/_ssh2.pyx", line 45, in _read_output
  File "ssh2\channel.pyx", line 116, in ssh2.channel.Channel.read
  File "ssh2\channel.pyx", line 144, in ssh2.channel.Channel.read_ex
  File "ssh2\utils.pyx", line 179, in ssh2.utils.handle_error_codes
ssh2.exceptions.SocketRecvError

### The code is the follow:

```
hosts = ['10.1.23.23', '10.1.23.24']
client = ParallelSSHClient(hosts, user='xx', password='xx')
command_stp = "show spanning-tree detail | inc ieee|occurr|from|is exec"
output = client.run_command(command_stp)

for host, host_output in output.items():
    for line in host_output.stdout:
        print(line)
```

When I run the code with only one hosts it works like a charm and doesn't raise any exceptions.

Switches model: WS-C3750X-48PF-S

Is it a common problem?

**Comment by vladimir-incountry** [comment]
It's pretty much the same for me. I do not get `SocketRecvError` when I run commands on one host, but I get it when I run it on multiple hosts.
It's weird because the command is the same. The exception occurs when I print STDOUT of the second host.
