### ISSUE TITLE
ssh2.exceptions.SCPProtocolError 

### ISSUE THREAD

**Issue by ShixiangWang** [ParallelSSH/ssh2-python#88]
Dear developer,

I encounter SCPProtocolError when I try to write a program for copying files to a remote host.

I also tried example code from https://github.com/ParallelSSH/ssh2-python/blob/master/examples/scp_write.py, I think it will be easier to reproduce. I tried auth using key file or password.

```
#!/usr/bin/python

"""Example script for SCP write"""

from __future__ import print_function

import argparse
import socket
import os
import sys
from datetime import datetime

from ssh2.session import Session

parser = argparse.ArgumentParser()


parser.add_argument('source', help="Source file to copy")
parser.add_argument('destination', help="Remote destination file to copy to")
parser.add_argument('--host', dest='host',
                    default='localhost',
                    help='Host to connect to')
parser.add_argument('--port', dest='port', default=22, help="Port to connect on", type=int)
parser.add_argument('-u', dest='user', default='wsx', help="User name to authenticate as")


def main():
    args = parser.parse_args()
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect((args.host, args.port))
    s = Session()
    s.handshake(sock)
    print(args.user)
    print(args.host)
    print(args.port)
    #s.userauth_publickey_fromfile(args.user, "~/.ssh/id_rsa")
    passwd = input('Enter your password: ')
    s.userauth_password(args.user, passwd)
    fileinfo = os.stat(args.source)
    chan = s.scp_send64(args.destination, fileinfo.st_mode & 0o777, fileinfo.st_size,
                        fileinfo.st_mtime, fileinfo.st_atime)
    print("Starting SCP of local file %s to remote %s:%s" % (
        args.source, args.host, args.destination))
    now = datetime.now()
    with open(args.source, 'rb') as local_fh:
        for data in local_fh:
            chan.write(data)
    taken = datetime.now() - now
    rate = (fileinfo.st_size / (1024000.0)) / taken.total_seconds()
    print("Finished writing remote file in %s, transfer rate %s MB/s" % (
        taken, rate))


if __name__ == "__main__":
    main()
```

Here is the error info. I don't know how to debug it.

```
PS C:\GitHub\loon\tests> python .\test_scp.py --host 10.19.24.165 .\conftest.py /home/test/upload/ 
wsx
10.19.24.165
22
Enter your password:
Traceback (most recent call last):
  File ".\test_scp.py", line 55, in <module>
    main()
  File ".\test_scp.py", line 41, in main
    fileinfo.st_mtime, fileinfo.st_atime)
  File "ssh2\session.pyx", line 553, in ssh2.session.Session.scp_send64
  File "ssh2\utils.pyx", line 151, in ssh2.utils.handle_error_codes
ssh2.exceptions.SCPProtocolError
```

The error comes from 

```
    chan = s.scp_send64(args.destination, fileinfo.st_mode & 0o777, fileinfo.st_size,
                        fileinfo.st_mtime, fileinfo.st_atime)
```

The file info looks good

```
os.stat_result(st_mode=33206, st_ino=562949953655768, st_dev=2013704423, st_nlink=1, 
st_uid=0, st_gid=0, st_size=235, st_atime=1569948206, st_mtime=1569948206, st_ctime=1569948206)
```

And I can run commands on the remote host by ssh2-python. Is there a bug or do I miss something?  I read docs about scp_send64 and exception but not find anything useful https://ssh2-python.readthedocs.io/en/latest/session.html

I do hope you can help me out.

Thanks.

Best,
Shixiang

**Comment by Red-M** [comment]
I've found `scp_send64()` really bad at reporting why exactly it has failed, generally it could be that you don't have write permissions in that location, the location doesn't exist (folder or path in general) or the permissions to write to the device.

I'd suggest doing a `touch` to location on the remote machine to see why its not letting you write there.

**Comment by ShixiangWang** [comment]
@Red-M Thanks your suggestion. Condering no reponse from maintainer for a long time, I will close this issue.
